nilenso/goose

- .github/workflows/publish.yml
- .gitignore
- README.md
- deps.edn
- pom.xml
- src/goose/broker.clj
- src/goose/client.clj
- src/goose/worker.clj
- test/goose/integration_test.clj
> Open Source Goose

- architecture-decisions/README.md
- architecture-decisions/pages/multiple-brokers.md
- src/goose/broker.clj
- src/goose/client.clj
- src/goose/defaults.clj
- src/goose/heartbeat.clj
- src/goose/job.clj
- src/goose/orphan_checker.clj
- src/goose/retry.clj
- src/goose/scheduler.clj
- src/goose/utils.clj
- src/goose/worker.clj
- test/goose/integration_test.clj
> ADR for Multiple Brokers

- architecture-decisions/pages/redis.md
- src/goose/specs.clj
- test/goose/specs_test.clj
> Finalize Redis client library

- architecture-decisions/pages/specs.md
- src/goose/api/dead_jobs.clj
- src/goose/api/enqueued_jobs.clj
- src/goose/api/scheduled_jobs.clj
- src/goose/brokers/broker.clj
- src/goose/brokers/redis/api/dead_jobs.clj
- src/goose/brokers/redis/api/enqueued_jobs.clj
- src/goose/brokers/redis/api/scheduled_jobs.clj
- src/goose/brokers/redis/client.clj
- src/goose/brokers/redis/executor.clj
- src/goose/brokers/redis/heartbeat.clj
- src/goose/brokers/redis/orphan_checker.clj
- src/goose/brokers/redis/retry.clj
- src/goose/brokers/redis/scheduler.clj
- src/goose/brokers/redis/statsd.clj
- src/goose/brokers/redis/worker.clj
- src/goose/client.clj
- src/goose/defaults.clj
- src/goose/executor.clj
- src/goose/retry.clj
- src/goose/specs.clj
- src/goose/statsd.clj
- src/goose/worker.clj
- test/goose/api_test.clj
- test/goose/redis/api_test.clj
- test/goose/redis/integration_test.clj
- test/goose/specs_test.clj
- test/goose/test_utils.clj
> Add Broker Protocol for Redis

- src/goose/brokers/redis/api/dead_jobs.clj
- src/goose/brokers/redis/api/scheduled_jobs.clj
- src/goose/brokers/redis/retry.clj
- src/goose/brokers/redis/scheduler.clj
- src/goose/brokers/redis/worker.clj
- src/goose/brokers/rmq/commands.clj
- src/goose/brokers/rmq/retry.clj
- src/goose/brokers/rmq/scheduler.clj
- src/goose/brokers/rmq/worker.clj
- src/goose/defaults.clj
- src/goose/job.clj
- src/goose/retry.clj
- src/goose/specs.clj
- test/goose/redis/integration_test.clj
- test/goose/rmq/integration_test.clj
> Error handling & Retrying

- src/goose/brokers/redis/broker.clj
- src/goose/brokers/redis/scheduler.clj
- src/goose/brokers/rmq/broker.clj
- src/goose/brokers/rmq/channel.clj
- src/goose/brokers/rmq/commands.clj
- src/goose/brokers/rmq/publisher_confirms.clj
- src/goose/brokers/rmq/retry.clj
- src/goose/brokers/rmq/scheduler.clj
- src/goose/brokers/rmq/worker.clj
- src/goose/client.clj
- src/goose/specs.clj
- test/goose/redis/api_test.clj
- test/goose/redis/integration_test.clj
- test/goose/rmq/integration_test.clj
- test/goose/specs_test.clj
- test/goose/test_utils.clj
> [rmq] Add publisher confirms

- src/goose/api/dead_jobs.clj
- src/goose/api/enqueued_jobs.clj
- src/goose/api/scheduled_jobs.clj
- src/goose/brokers/broker.clj
- src/goose/brokers/redis/api/dead_jobs.clj
- src/goose/brokers/redis/api/enqueued_jobs.clj
- src/goose/brokers/redis/api/scheduled_jobs.clj
- src/goose/brokers/redis/broker.clj
- src/goose/brokers/redis/commands.clj
- src/goose/brokers/rmq/api/dead_jobs.clj
- src/goose/brokers/rmq/api/enqueued_jobs.clj
- src/goose/brokers/rmq/broker.clj
- src/goose/brokers/rmq/publisher_confirms.clj
- src/goose/brokers/rmq/retry.clj
- test/goose/redis/api_test.clj
- test/goose/redis/integration_test.clj
- test/goose/rmq/api_test.clj
- test/goose/rmq/integration_test.clj
> API to manage RabbitMQ jobs

- src/goose/brokers/redis/worker.clj
- src/goose/brokers/rmq/worker.clj
> Add metrics for RabbitMQ broker

- src/goose/batch.clj
- src/goose/broker.clj
- src/goose/client.clj
Closes #113.
Implements Goose Client APIs to enqueue jobs in Batches.
> Client batch API 

- src/goose/brokers/redis/batch.clj
- src/goose/brokers/redis/commands.clj
- src/goose/brokers/redis/retry.clj
- src/goose/brokers/redis/worker.clj
- src/goose/defaults.clj
- src/goose/job.clj
- src/goose/retry.clj
The middleware updates the batch state accordingly.
Closes #117
> Batch status update post execution of job

- src/goose/brokers/redis/commands.clj
- test/goose/brokers/redis/batch_test.clj
- test/goose/brokers/redis/integration_test.clj
Add integration tests for,
1. Happy path of `perform-batch`
2. `redis.batch/enqueue`
Is a part of https://github.com/nilenso/goose/issues/128
> Batching integration tests

- test/goose/brokers/redis/batch_test.clj
Covers unit tests for update-state middleware where job moves from 
1. enqueued -> successful
2. enqueued -> retrying
3. enqueued -> dead
4. retrying -> successful
5. retrying -> retrying
6. retrying -> dead
> Unit tests for batch middleware

- src/goose/api/batch.clj
- src/goose/batch.clj
- src/goose/brokers/redis/api/batch.clj
- src/goose/brokers/redis/api/dead_jobs.clj
- src/goose/brokers/redis/api/scheduled_jobs.clj
- src/goose/brokers/redis/batch.clj
- src/goose/brokers/redis/commands.clj
- src/goose/brokers/redis/scheduler.clj
- src/goose/brokers/redis/worker.clj
- src/goose/brokers/rmq/broker.clj
- src/goose/brokers/rmq/commands.clj
- src/goose/brokers/rmq/retry.clj
- src/goose/client.clj
- src/goose/defaults.clj
- src/goose/job.clj
- src/goose/metrics.clj
- src/goose/retry.clj
- src/goose/specs.clj
- src/goose/utils.clj
- test/goose/brokers/redis/api_test.clj
- test/goose/brokers/redis/batch_test.clj
- test/goose/brokers/redis/integration_test.clj
1. Implements post batch execution logic using distributed locking in Redis:
- Callback
- Set expiration on batch data
2. Add batch-state to `wrap-state-update` unit test setup
3. Add Redis commands for hashes, expiration and ttl
Closes #118
Closes #132
> Batch callback

- architecture-decisions/pages/api.md
- architecture-decisions/pages/periodic-jobs.md
- src/goose/api/batch.clj
- src/goose/api/cron_jobs.clj
- src/goose/api/enqueued_jobs.clj
- src/goose/broker.clj
- src/goose/brokers/redis/api/batch.clj
- src/goose/brokers/redis/api/dead_jobs.clj
- src/goose/brokers/redis/api/enqueued_jobs.clj
- src/goose/brokers/redis/api/scheduled_jobs.clj
- src/goose/brokers/redis/batch.clj
- src/goose/brokers/redis/broker.clj
- src/goose/brokers/redis/commands.clj
- src/goose/brokers/redis/cron.clj
- src/goose/brokers/redis/heartbeat.clj
- src/goose/brokers/redis/orphan_checker.clj
- src/goose/job.clj
- src/goose/utils.clj
- test/goose/brokers/redis/api_test.clj
- test/goose/test_utils.clj
> Batch delete api

- src/goose/api/batch.clj
- src/goose/batch.clj
- src/goose/brokers/redis/batch.clj
- src/goose/brokers/redis/commands.clj
- src/goose/brokers/redis/metrics.clj
- src/goose/defaults.clj
- src/goose/metrics.clj
- src/goose/utils.clj
- test/goose/brokers/redis/api_test.clj
- test/goose/brokers/redis/batch_test.clj
- test/goose/brokers/redis/integration_test.clj
> Emit metrics for Batch jobs

- deps.edn
- test/goose/brokers/redis/console_test.clj
- test/goose/console_test.clj
The changes are build on top of the PR #148
> Console views test

- test/goose/console_test.clj
Expected failed jobs still exist in enqueued jobs queue
> Fix: Expected failed jobs still exist in enqueued jobs queue 

- architecture-decisions/pages/console.md
Add an ADR for console to highlight `design decisions`, `avoided design` and more.
> ADR for console

- CHANGELOG.md
- README.md
- pom.xml
> Ready Goose for 0.5.1 release

- src/goose/brokers/redis/api/dead_jobs.clj
- src/goose/brokers/redis/api/scheduled_jobs.clj
- src/goose/brokers/redis/commands.clj
- src/goose/console.clj
- test/goose/brokers/redis/api_test.clj
- test/goose/brokers/redis/commands_test.clj
- test/goose/factories.clj
> Dead jobs API to operate on >1 job

- resources/public/css/style.css
- resources/public/js/index.js
- src/goose/brokers/redis/console.clj
- src/goose/brokers/redis/console/data.clj
- src/goose/brokers/redis/console/pages/components.clj
- src/goose/brokers/redis/console/pages/dead.clj
- src/goose/brokers/redis/console/pages/enqueued.clj
- src/goose/brokers/redis/console/specs.clj
- src/goose/console.clj
- test/goose/brokers/redis/console/data_test.clj
- test/goose/brokers/redis/console/page_test.clj
View dead jobs in console:
View [here](http://139.59.73.117:3000/) to check console in staging.
> View dead jobs for redis

- resources/public/js/index.js
- src/goose/brokers/redis/console/data.clj
- src/goose/brokers/redis/console/pages/components.clj
- src/goose/brokers/redis/console/pages/enqueued.clj
- test/goose/brokers/redis/console/data_test.clj
The PR addresses:
- Fixing the console view breaking when filter by id when no jobs in redis
- Frontend validation to make filter-value compulsory to apply filter
- Improve readability in filter fns by breaking into smaller fns
> Fix filter bug

- resources/public/css/style.css
- src/goose/brokers/redis/console/pages/components.clj
- src/goose/brokers/redis/console/pages/dead.clj
- src/goose/brokers/redis/console/pages/enqueued.clj
- src/goose/brokers/rmq/console.clj
- src/goose/console.clj
- test/goose/brokers/redis/api_test.clj
- test/goose/brokers/redis/console/data_test.clj
- test/goose/brokers/redis/console/page_test.clj
- test/goose/brokers/rmq/console_test.clj
- test/goose/factories.clj
> Rmq dead job page

- src/goose/brokers/redis/api/scheduled_jobs.clj
- src/goose/brokers/redis/commands.clj
- src/goose/console.clj
- test/goose/brokers/redis/api_test.clj
- test/goose/brokers/redis/commands_test.clj
- test/goose/factories.clj
Add delete/get/prioritise apis for >1 scheduled jobs
> Add delete/get/prioritise apis for >1 scheduled jobs 

- resources/public/css/style.css
- resources/public/js/index.js
- src/goose/brokers/redis/console.clj
- src/goose/brokers/redis/console/data.clj
- src/goose/brokers/redis/console/pages/components.clj
- src/goose/brokers/redis/console/pages/home.clj
- src/goose/brokers/redis/console/pages/scheduled.clj
- src/goose/brokers/redis/console/specs.clj
- src/goose/utils.clj
- test/goose/brokers/redis/console/data_test.clj
- test/goose/brokers/redis/console/page_test.clj
View and filter scheduled jobs
> Paginated view of scheduled jobs

- resources/public/css/style.css
- resources/public/js/index.js
- src/goose/brokers/redis/console/pages/batch.clj
- src/goose/brokers/redis/console/pages/cron.clj
- src/goose/brokers/redis/console/pages/dead.clj
- src/goose/brokers/redis/console/pages/enqueued.clj
- src/goose/brokers/redis/console/pages/home.clj
- src/goose/brokers/redis/console/pages/scheduled.clj
- src/goose/brokers/rmq/console.clj
- src/goose/console.clj
PR adds 
- dark/light theme to console
- option to poll console page data in x intervals
> Implement dark/light theme to console
